image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - scala-lang.scala@0.5.0:3FIiaU1vnooQsX3PkBlBvQ==
    - scalameta.metals@1.10.8:wOYpsld/e93zZ250A0uKHA==
ports:
  - port: 9000
    onOpen: ignore